### ISSUE TITLE
Chapter 6 and others: explanations of plots

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#11]
When you describe 2d Ceteris Paribus (Section 6.3), you say:
"Such multi-dimensional extensions are useful to check if, for instance, the model involves interactions. "
It would be helpful to explain when we can say that a Ceteris Paribus 2D plot indicates interaction. 

How about adding a subsection in every chapter where different scenarios are shown with explanations what the reader should deduce from each plot? 
Or at least extensively explain plots presented in "Method" sections in every chapter.

**Comment by pbiecek** [comment]
Thanks, the CP 2d are moved to supplementary materials (likely to remove)
