### ISSUE TITLE
Chapter 6: plots in Code snippets for R

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#12]
1) I think that it would be good to show variable-importance measures for 2d Ceteris Paribus plots. Especially as 2d vip is described in Section 6.3 Method.

2) When you show 2D CP profiles for `age` `sibsp` and `parch` you say that  "both variables `age` and `sibsp` are important and influence the model response." 
Why did you omit variable parch? When I look at plot `age` vs `parch` I would say that `age` and `parch` have the largest mutual influence. Maybe I am wrong with assessing their influence, so VIP plot would be helpful, as I mentioned in 1) :wink:

![image](https://user-images.githubusercontent.com/18423383/56423333-e1478080-62ab-11e9-9bc0-d548efa46703.png)

**Comment by pbiecek** [comment]
Interesting idea,
currently 2d plots are hard to read (same problem with pdp)
one idea is to present residuals after main effects (additive) are removed. But it's not implemented now

**Comment by pbiecek** [comment]
Thanks. CP2D were removed as this chapter was not consistent with other chapters
