### ISSUE TITLE
Chapter 7: extended description of Nearest neighbors

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#14]
Subsection 7.3.1 Nearest neighbors

1) Are there any heuristics related to the number of neighbors?

2) what is $d_k$ distance? Normalized Euclidean distance?
I thought the in gover distance numerical and categorical variables are treated differently. But I'm not sure.

3) If the gover distance is a default measure, so what are alternatives? And why is it default?

**Comment by pbiecek** [comment]
fixed in 320ba5

**Comment by pbiecek** [comment]
Thanks
