### ISSUE TITLE
Chapter 7: notation in Section 7.3.3 Residuals

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#15]
You wrote:
![image](https://user-images.githubusercontent.com/18423383/56425853-4c965000-62b6-11e9-8e51-08dd38afc88e.png)
It is inconsistent with notation introduced in Section 4.3. 
Index of the observation should be lower, not upper.

You also wrote:
"In addition we can add examination of the local residuals that assess local model fit."
What examination?
I think that this section should be extended.

**Comment by pbiecek** [comment]
Thanks fixed
