### ISSUE TITLE
Chapter 7: order of params in `select_neighbours()` function

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#16]
I am opening the issue here, but I do not know whether it should not be in the repository of the `ingredients` package.

I think that the first parameter of the `select_neighbours()` function should be an `observation` instead of `data`.

Now, the convention in ingredients is that the name of the function is somehow related to the first parameter.
`plot()` (what?) `ceteris_paribus_explainer`
`print()` (what?) `ceteris_paribus_explainer`
`calculate_oscilations()` (of what?) `ceteris_paribus_explainer`

and for `select_neighbours()` it should be the same
`calculate_neighbours()` (of what?) `observation`

**Comment by pbiecek** [comment]
good point, I should add it somewhere (DrWhy repo?)

**Comment by pbiecek** [comment]
Thanks, corrected
