### ISSUE TITLE
Chapter  1-2: misc suggestions

### ISSUE THREAD

**Issue by kasiapekala** [pbiecek/PM_VEE#20]
1.4 Terminology 
This part could address "coefficient" - term heavily used in the following section about black/glass boxes.

2.3 How to work with archivist?
Last sentence could also mention that data for model explainers (for which archivist hooks are used) is described in detail in chapter 4. 

Typos:
1.8 notation, first paragraph
In some cases this may result in formulae **wth** a fairly complex system of indices.
(should be "with")

1.9 The structure, 5th paragraph
Chapter 12 **presens** a different approach to explanation
(should be "presents")

**Comment by pbiecek** [comment]
Thanks!
