### ISSUE TITLE
Chapter 7: misc

### ISSUE THREAD

**Issue by kasiapekala** [pbiecek/PM_VEE#33]
https://github.com/pbiecek/PM_VEE/blob/76c1580556f90b207b6f2d96fc9b7110fb0263bc/06-Ceteris-paribus-Profiles.Rmd#L172

Plot produces warnings. From what I see, "only_numerical" is not a plot.ceteris_paribus_explainer parameter anymore.

maybe it could be changed to:

```
plot(cp_titanic_rf, variables = c("class", "embarked"), variable_type = "categorical") +
+   ggtitle("Ceteris Paribus Profiles", "For the random forest model and the Titanic dataset")

```
Also here is reference to only_numerical as plot parameter:
https://github.com/pbiecek/PM_VEE/blob/76c1580556f90b207b6f2d96fc9b7110fb0263bc/06-Ceteris-paribus-Profiles.Rmd#L169

---

Second thing:

https://github.com/pbiecek/PM_VEE/blob/76c1580556f90b207b6f2d96fc9b7110fb0263bc/06-Ceteris-paribus-Profiles.Rmd#L57
repeats
https://github.com/pbiecek/PM_VEE/blob/76c1580556f90b207b6f2d96fc9b7110fb0263bc/06-Ceteris-paribus-Profiles.Rmd#L59

**Comment by pbiecek** [comment]
Thank you, both corrested
