### ISSUE TITLE
Chapter 1: outdated description of the chapter structure

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#5]
In *1.8 The structure of the book* you describe the division of sections for methods into subsections named:
- Introduction
- The Algorithm
- Example
- Pros and Cons
- Code snippets

While the subsections in sections 1-7 are: 
- Introduction
- Intuition
- Method
- Pros and cons
- Code snippets for R

**Comment by pbiecek** [comment]
Thanks, fixed
