### ISSUE TITLE
Chapter 4:  Panel A of Figure 4.1

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#6]
I really don't like 3d plot A in Figure 4.1. :wink:
Currently,  z-axis (model response) is nearly useless, I can't read values. 
And because of the 3d structure of the plot, I can't see what if `class==' 'victualling crew'` or `class=='restaurant staff'`.
How would it look like as a heatmap? 

Or, as we were talking during the seminary, 3d plod could be interactive or at least a gif. But what about a paper version of the book?

![image](https://user-images.githubusercontent.com/18423383/56423366-00dea900-62ac-11e9-9536-6bec8c8fde70.png)

**Comment by pbiecek** [comment]
It's a gif now. No idea how this will transplate to the paper version, but let's have good online version first
