### ISSUE TITLE
Chapter 4: similarity of ceteris paribus and lime

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#7]
In subsection 4.2 there is a comparison of CP and LIME, however, you present LIME 8 chapters later (chapter 12).
Wouldn't it be better to place this comparison in chapter 12? 
If someone reads one chapter after another, he would not have to jump between chapters.
**or**
How about adding a separate chapter to point out similarities and differences between local methods? e.g. CP and LIME, LIME and SHAP, LIME and localModel, etc.

**Comment by pbiecek** [comment]
Thnaks!
