### ISSUE TITLE
Chapter 4: how to interpret CP for discrete vars

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#8]
You've described how to interpret CP for a continuous variable (Figure 4.2). 
> Moreover, for this instance (observation), the prediction would increase substantially if the value of the explanatory variable became lower than 20.

I think that there should be a similar short interpretation for CP for a discrete variable in Figure 4.3.

Side note:
For continuous variables, a model response is on the y-axis, for discrete on the x-axis. Can this be unified?

**Comment by pbiecek** [comment]
Regards unification:  that's hard, because for categorical variables it is much easier to read horizontal names (so y in on OX) while for continues variables it's easier to see function with values on OY.
Any suggestions how this can be unified? 
I will talk about this with Hanna this week.

**Comment by pbiecek** [comment]
Short interpretation for the figure is added. Thanks!
