### ISSUE TITLE
Chapter 4: extending 'Pros and cons' section

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/PM_VEE#9]
I think that section with pros should be extended, now the only highlighted advantage is easiness of understanding. If it is the only advantage, why should we use CP? If at all.

When you point out the cons of 1d CP, it would be good to give examples for better understanding.
For example, when you mention "unrealistic settings", you can say about a situation, where CP consider an apartment with 4 rooms and 20m2.

**Comment by pbiecek** [comment]
Thanks, description extended
